# Generated by Django 4.1.2 on 2022-10-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('en_bilgisayar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all',
            name='item_model_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='all',
            name='item_name',
            field=models.CharField(max_length=255),
        ),
    ]
