# Generated by Django 4.1.2 on 2022-10-28 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('en_ucuz', '0002_alter_blog_category_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
